name: Create a (Pre)release on NuGet (Core)

on:
  push:
    tags:
      - "core_[0-9]+.[0-9]+.[0-9]+"
      - "core_[0-9]+.[0-9]+.[0-9]+-beta"
      - "core_[0-9]+.[0-9]+.[0-9]+-beta[0-9]+"
      - "core_[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"

jobs:
  release-core:
    runs-on: windows-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Verify commit exists in origin/main or origin/develop
        run: |
          git fetch --no-tags --prune origin +refs/heads/*:refs/remotes/origin/*
          $branches = git branch --remote --contains
          if (-not ($branches | Select-String -Pattern 'origin/main|origin/develop')) {
            Write-Error "Tagged commit is not contained in origin/main or origin/develop"
            exit 1
          }

      - name: Get version information from tag
        id: get_version
        run: |
          $version = "${{ github.ref_name }}" -replace '^core_', ''
          "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Restore dependencies
        run: dotnet restore src\core\NepaliUtility.Core.csproj

      - name: Build library
        run: dotnet build src\core\NepaliUtility.Core.csproj -c Release /p:Version=${{ steps.get_version.outputs.version }}

      - name: Pack library
        run: dotnet pack src\core\NepaliUtility.Core.csproj -c Release /p:Version=${{ steps.get_version.outputs.version }} --no-build --output .

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push
        run: dotnet nuget push "*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate
